CrudAlumnos/Controllers/CGradoAlumnoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrudAlumnos.AlumnosContext;
using CrudAlumnos.Models;

namespace CrudAlumnos.Controllers
{
    public class CGradoAlumnoesController : Controller
    {
        private AlumnosC db = new AlumnosC();

        // GET: CGradoAlumnoes
        public ActionResult Index()
        {
            return View(db.CGradoAlumnoes.ToList());
        }

        // GET: CGradoAlumnoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CGradoAlumno cGradoAlumno = db.CGradoAlumnoes.Find(id);
            if (cGradoAlumno == null)
            {
                return HttpNotFound();
            }
            return View(cGradoAlumno);
        }

        // GET: CGradoAlumnoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CGradoAlumnoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDGrado,GradoAlumno")] CGradoAlumno cGradoAlumno)
        {
            if (ModelState.IsValid)
            {
                db.CGradoAlumnoes.Add(cGradoAlumno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cGradoAlumno);
        }

        // GET: CGradoAlumnoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CGradoAlumno cGradoAlumno = db.CGradoAlumnoes.Find(id);
            if (cGradoAlumno == null)
            {
                return HttpNotFound();
            }
            return View(cGradoAlumno);
        }

        // POST: CGradoAlumnoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDGrado,GradoAlumno")] CGradoAlumno cGradoAlumno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cGradoAlumno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cGradoAlumno);
        }

        // GET: CGradoAlumnoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CGradoAlumno cGradoAlumno = db.CGradoAlumnoes.Find(id);
            if (cGradoAlumno == null)
            {
                return HttpNotFound();
            }
            return View(cGradoAlumno);
        }

        // POST: CGradoAlumnoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CGradoAlumno cGradoAlumno = db.CGradoAlumnoes.Find(id);
            db.CGradoAlumnoes.Remove(cGradoAlumno);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CrudAlumnos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Registro Alumnos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Registro Grado", "Index", "CGradoAlumnoes")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>